In [50]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

In [51]:
df=pd.read_csv("telco_data.csv")
df.head()

SeniorCitizen  MonthlyCharges  TotalCharges  Churn  gender_Female  \
0              0           29.85         29.85      0           True   
1              0           56.95       1889.50      0          False   
2              0           53.85        108.15      1          False   
3              0           42.30       1840.75      0          False   
4              0           70.70        151.65      1           True   

   gender_Male  Partner_No  Partner_Yes  Dependents_No  Dependents_Yes  ...  \
0        False       False         True           True           False  ...   
1         True        True        False           True           False  ...   
2         True        True        False           True           False  ...   
3         True        True        False           True           False  ...   
4        False        True        False           True           False  ...   

   PaymentMethod_Bank transfer (automatic)  \
0                                    False   
1                                    False   
2                                    False   
3                                     True   
4                                    False   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                  False                            True   
1                                  False                           False   
2                                  False                           False   
3                                  False                           False   
4                                  False                            True   

   PaymentMethod_Mailed check  tenure_group_1 - 12  tenure_group_13 - 24  \
0                       False                 True                 False   
1                        True                False                 False   
2                        True                 True                 False   
3                       False                False                 False   
4                       False                 True                 False   

   tenure_group_25 - 36  tenure_group_37 - 48  tenure_group_49 - 60  \
0                 False                 False                 False   
1                  True                 False                 False   
2                 False                 False                 False   
3                 False                  True                 False   
4                 False                 False                 False   

   tenure_group_61 - 72  
0                 False  
1                 False  
2                 False  
3                 False  
4                 False  

[5 rows x 51 columns]

In [52]:
x=df.drop('Churn',axis=1)
x

SeniorCitizen  MonthlyCharges  TotalCharges  gender_Female  gender_Male  \
0                 0           29.85         29.85           True        False   
1                 0           56.95       1889.50          False         True   
2                 0           53.85        108.15          False         True   
3                 0           42.30       1840.75          False         True   
4                 0           70.70        151.65           True        False   
...             ...             ...           ...            ...          ...   
7027              0           84.80       1990.50          False         True   
7028              0          103.20       7362.90           True        False   
7029              0           29.60        346.45           True        False   
7030              1           74.40        306.60          False         True   
7031              0          105.65       6844.50          False         True   

      Partner_No  Partner_Yes  Dependents_No  Dependents_Yes  PhoneService_No  \
0          False         True           True           False             True   
1           True        False           True           False            False   
2           True        False           True           False            False   
3           True        False           True           False             True   
4           True        False           True           False            False   
...          ...          ...            ...             ...              ...   
7027       False         True          False            True            False   
7028       False         True          False            True            False   
7029       False         True          False            True             True   
7030       False         True           True           False            False   
7031        True        False           True           False            False   

      ...  PaymentMethod_Bank transfer (automatic)  \
0     ...                                    False   
1     ...                                    False   
2     ...                                    False   
3     ...                                     True   
4     ...                                    False   
...   ...                                      ...   
7027  ...                                    False   
7028  ...                                    False   
7029  ...                                    False   
7030  ...                                    False   
7031  ...                                     True   

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                     False                            True   
1                                     False                           False   
2                                     False                           False   
3                                     False                           False   
4                                     False                            True   
...                                     ...                             ...   
7027                                  False                           False   
7028                                   True                           False   
7029                                  False                            True   
7030                                  False                           False   
7031                                  False                           False   

      PaymentMethod_Mailed check  tenure_group_1 - 12  tenure_group_13 - 24  \
0                          False                 True                 False   
1                           True                False                 False   
2                           True                 True                 False   
3                          False                False                 False   
4                          False                 True              

In [53]:
y=df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


Decision Tree Classifier

In [55]:
model_dt=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)


In [56]:
model_dt.fit(x_train,y_train)


DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [57]:

y_pred=model_dt.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [58]:
model_dt.score(x_test,y_test)


0.8045486851457001

Accuracy is Low. Since it is imbalanced data we have to classification report

In [59]:
print(classification_report(y_test, y_pred, labels=[0,1]))


              precision    recall  f1-score   support

           0       0.83      0.93      0.88      1040
           1       0.69      0.46      0.55       367

    accuracy                           0.80      1407
   macro avg       0.76      0.69      0.71      1407
weighted avg       0.79      0.80      0.79      1407



to upsample by generating synthetic data

In [60]:
sm = SMOTEENN()
X_resampled, y_resampled = sm.fit_resample(x,y)


In [61]:
xr_train,xr_test,yr_train,yr_test=train_test_split(X_resampled, y_resampled,test_size=0.2)


In [62]:
model_dt_smote=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)


In [63]:
model_dt_smote.fit(xr_train,yr_train)
yr_predict = model_dt_smote.predict(xr_test)
model_score_r = model_dt_smote.score(xr_test, yr_test)
print(model_score_r)
print(metrics.classification_report(yr_test, yr_predict))

0.9233390119250426
              precision    recall  f1-score   support

           0       0.93      0.90      0.91       531
           1       0.92      0.94      0.93       643

    accuracy                           0.92      1174
   macro avg       0.92      0.92      0.92      1174
weighted avg       0.92      0.92      0.92      1174



In [64]:
print(metrics.confusion_matrix(yr_test, yr_predict))


[[479  52]
 [ 38 605]]


Random Forest Classifier

In [65]:
from sklearn.ensemble import RandomForestClassifier


In [66]:
model_rf=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)


In [67]:
model_rf.fit(x_train,y_train)


RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [68]:
y_pred=model_rf.predict(x_test)


In [69]:
model_rf.score(x_test,y_test)


0.8152096659559346

In [70]:
print(classification_report(y_test, y_pred, labels=[0,1]))


              precision    recall  f1-score   support

           0       0.83      0.94      0.88      1040
           1       0.73      0.46      0.56       367

    accuracy                           0.82      1407
   macro avg       0.78      0.70      0.72      1407
weighted avg       0.81      0.82      0.80      1407



In [71]:
sm = SMOTEENN()
X_resampled1, y_resampled1 = sm.fit_resample(x,y)

In [72]:
xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(X_resampled1, y_resampled1,test_size=0.2)


In [73]:
model_rf_smote=RandomForestClassifier(n_estimators=200, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)


In [74]:
model_rf_smote.fit(xr_train1,yr_train1)


RandomForestClassifier(max_depth=6, min_samples_leaf=8, n_estimators=200,
                       random_state=100)

In [75]:
yr_predict1 = model_rf_smote.predict(xr_test1)


In [76]:
model_score_r1 = model_rf_smote.score(xr_test1, yr_test1)


In [77]:
print(model_score_r1)


0.9376601195559351


In [78]:
print(metrics.classification_report(yr_test1, yr_predict1))


              precision    recall  f1-score   support

           0       0.96      0.90      0.93       537
           1       0.92      0.97      0.94       634

    accuracy                           0.94      1171
   macro avg       0.94      0.93      0.94      1171
weighted avg       0.94      0.94      0.94      1171



In [79]:
print(metrics.confusion_matrix(yr_test1, yr_predict1))


[[484  53]
 [ 20 614]]


In [80]:
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import accuracy_score
predictions = model_rf_smote.predict(x_test)
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")
probabilities = model_rf_smote.predict_proba(x_test)[:, 1]
threshold = 0.4  # Change this threshold
predictions_adjusted = (probabilities >= threshold).astype(int)

print(f"Adjusted Accuracy: {accuracy_score(y_test, predictions_adjusted) * 100:.2f}%")


Accuracy: 75.84%
Adjusted Accuracy: 72.42%


With RF Classifier, also we got good results, better than Decision Tree.

we are selecting RandomForest Classifier

Pickling the model

In [81]:
import pickle

In [82]:
filename="churn_model.pkl"

In [83]:
pickle.dump(model_rf_smote, open(filename, 'wb'))

In [84]:
load_model = pickle.load(open(filename, 'rb'))


In [85]:
model_score_r1 = load_model.score(xr_test1, yr_test1)
model_score_r1

0.9376601195559351

In [86]:
feature_columns = df.columns.tolist()  
with open('feature_columns.pkl', 'wb') as file:
    pickle.dump(feature_columns, file)